-- MySQL Script generated by MySQL Workbench
-- dim. 30 sept. 2018 20:27:16 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`organization` ;

CREATE TABLE IF NOT EXISTS `mydb`.`organization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `short_intro` TINYTEXT NULL,
  `intro` TEXT(65535) NULL,
  `transport_access` TINYTEXT NULL,
  `address1_details` VARCHAR(128) NULL,
  `address2_number_town` VARCHAR(128) NULL,
  `address3_city_state` VARCHAR(128) NULL,
  `address4_zip_country` VARCHAR(128) NULL,
  `since_year` VARCHAR(45) NULL,
  `students_nb` VARCHAR(16) NULL,
  `students_nations` VARCHAR(128) NULL,
  `students_by_class` VARCHAR(16) NULL,
  `study_penetration_rate` VARCHAR(16) NULL,
  `housing_fees` VARCHAR(128) NULL,
  `additionnal_infos` TINYTEXT NULL,
  `map_shortcode` TEXT(65535) NULL,
  `feedback1` TINYTEXT NULL,
  `feedback2` TINYTEXT NULL,
  `feedback3` TINYTEXT NULL,
  `type` ENUM('school', 'housing', 'spot') NULL,
  `residents_nb` VARCHAR(16) NULL,
  `residents_nations` VARCHAR(128) NULL,
  `residents_by_room` VARCHAR(16) NULL,
  `rental_fee` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `passwd_hash` VARCHAR(128) NOT NULL,
  `passwd_salt` VARCHAR(128) NOT NULL,
  `role` ENUM('admin', 'nonadmin') NULL,
  `name` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cursus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cursus` (
  `duration` VARCHAR(45) NULL,
  `selection_fee` INT NULL,
  `admission_fee` INT NULL,
  `lesson_fee` INT NULL,
  `other_fee` INT NULL,
  `organization_id` INT NOT NULL,
  `purpose` TINYTEXT NULL,
  PRIMARY KEY (`organization_id`),
  INDEX `fk_cursus_organization_idx` (`organization_id` ASC),
  CONSTRAINT `fk_cursus_organization`
    FOREIGN KEY (`organization_id`)
    REFERENCES `mydb`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`news` ;

CREATE TABLE IF NOT EXISTS `mydb`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `keywords` TINYTEXT NULL,
  `title` VARCHAR(128) NULL,
  `content` TEXT(65535) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_news_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_news_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`faq` ;

CREATE TABLE IF NOT EXISTS `mydb`.`faq` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(128) NULL,
  `answer` TEXT(65535) NULL,
  `keywords` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`photo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alt_text` VARCHAR(64) NOT NULL,
  `url` TINYTEXT NULL,
  `keywords` TINYTEXT NULL,
  `organization_id` INT NOT NULL,
  PRIMARY KEY (`id`, `organization_id`),
  INDEX `fk_photo_organization1_idx` (`organization_id` ASC),
  CONSTRAINT `fk_photo_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `mydb`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
